//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_HutBazar.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EhutBazardbEntities : DbContext
    {
        public EhutBazardbEntities()
            : base("name=EhutBazardbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Request_Shopowner> Request_Shopowner { get; set; }
        public DbSet<ShopOwner> ShopOwner { get; set; }
        public DbSet<User_Admin> User_Admin { get; set; }
    }
}
