//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_HutBazar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShopOwner
    {
        public string ShopO_Username { get; set; }
        public string ShopO_Password { get; set; }
    }
}
